spring:
  application:
    name: books
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:books;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: never

aladin:
  api:
    key: ENC(L6ztXJXEDUzurinyR6rhd9V99PEBzgxY0sI6S2Ptllw=)

server:
  port: 8083

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:1234@localhost:8761/eureka
      #,http://admin:1234@localhost:8762/eureka
  instance:
    prefer-ip-address: false
