spring:
  datasource:
    url: ENC(G/rh9H8G7vkNa2gWM40xVeBDfHcws8/a3d1RPpWULMKUtuGs2JptuCbARCNuVTkDXQr/dKqZaCqee/h35eVDFGpd2rSLRrDwAmcYZt9bAG74WrtOzZE6L6+HPClibGk3KZg5rQT1HSg=)
    username: ENC(E7wzC9kl4nVwfEV7JsZ09WVAXwAQhSwy)
    password: ENC(udeUrEU3cfiVaNkqv4zwgEhifPvD2iRzsL5Jr/E2/u4=)
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      initial-size: 10
      max-total: 200
      max-idle: 10
      min-idle: 10
      validation-query: SELECT 1
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      log-expired-connections: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      host: 133.186.241.167
      port: 6379
      password: "*N2vya7H@muDTwdNMR!"
      database: 133

  elasticsearch:
    index: nuribooks

cloud:
  nhn:
    rabbitmq:
      secret-id: 438c2a33bc784910b27ec16502153d96

logging:
  level:
    root: info
