spring:
  datasource:
    url: jdbc:mysql://133.186.241.167:3306/project_be7_nuribooks_prod?useSSL=false&serverTimezone=UTC
    username: ENC(E7wzC9kl4nVwfEV7JsZ09WVAXwAQhSwy)
    password: ENC(udeUrEU3cfiVaNkqv4zwgEhifPvD2iRzsL5Jr/E2/u4=)
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      initial-size: 10
      max-total: 200
      max-idle: 10
      min-idle: 10
      validation-query: SELECT 1
      test-on-borrow: true
      test-on-return: false
      test-while-idle: true
      log-expired-connections: true
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      host: 133.186.241.167
      port: 6379
      password: "*N2vya7H@muDTwdNMR!"
      database: 140

  elasticsearch:
    index: nuri-books

cloud:
  nhn:
    rabbitmq:
      secret-id: 29fb0406fff74a6f81c66aa639396d69

logging:
  level:
    root: warn