spring:
  datasource:
    url: ENC(4dT7SywLidx3dSAGeNMmAFO9r4v5+NKxcGkQhrCyEsrCAAErk9mtsimvM+XYZkHP04maNVDqTLE59hkPE4crGBUe+3Efb5KU/UJHKZaL/XzE3zJlC5+TxGq4yZbZ/q+9/1vX4Y/yE8s=)
    username: ENC(E7wzC9kl4nVwfEV7JsZ09WVAXwAQhSwy)
    password: ENC(udeUrEU3cfiVaNkqv4zwgEhifPvD2iRzsL5Jr/E2/u4=)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect